# Práctica Clase 3

## Numpy

In [109]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [110]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.arange(10)

#Operaciones tanto en array de Numpy como en listas u operaciones que NO
#Suma, resta, multiplicacion, potencias: SI
#a + b
#a - b
#a * 2
#a ** 2

#Copiar array: SI
c = a.copy()
#c

#Suma de todos los elementos
a.sum()

#Agregar elementos: NO
d = np.arange(20)

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [111]:
arr1 = np.arange(10)
#arr1
arr2 = np.linspace(0, 9, 100)
#arr2

a**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [112]:
arr3 = np.arange(10, 101)
arr3[arr3 % 3 == 0]

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

In [113]:
print("Ej 1")

#Ej 1
print(np.__version__)
print("\n")

print("Ej 2")
#Ej 2
print(np.arange(10))
print("\n")

print("Ej 3")
#Ej 3
print(np.full((3,3), True, dtype = bool))
print("\n")

print("Ej 4")
#Ej 4
print(arr1[arr1 % 2 == 1])
print("\n")

print("Ej 5")
#Ej 5
arr1[arr1 % 2 == 1] = -1 #-1 en los impares
print(arr1)
print("\n")

Ej 1
1.23.5


Ej 2
[0 1 2 3 4 5 6 7 8 9]


Ej 3
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Ej 4
[1 3 5 7 9]


Ej 5
[ 0 -1  2 -1  4 -1  6 -1  8 -1]




In [114]:

print("Ej 6")
#Ej 6
arr4 = np.arange(10)
out = np.where(arr4 % 2 == 1, -1, arr4)
print(f"Original: {arr4}. Modificado: {out}")

print("\n")
print("Ej 7")
#Ej 7
print(arr4.reshape((2,-1)))
print("\n")

print("Ej 8")
#Ej 8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate([a,b], axis = 0))
print("\n")

print("Ej 9")
#Ej 9
print(np.concatenate([a,b], axis = 1))
print("\n")

print("Ej 10")
#Ej 10
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

Ej 6
Original: [0 1 2 3 4 5 6 7 8 9]. Modificado: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


Ej 7
[[0 1 2 3 4]
 [5 6 7 8 9]]


Ej 8
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Ej 9
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Ej 10


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html